### ISSUE TITLE
NotAcceptableError

### ISSUE THREAD

**Issue by Globegitter** [geelen/jspm-server#23]
I am just starting to play around with System.js and jspm-server, I love the idea and the direction this is going.

Still working out if we can integrate this into our existing project but I am getting some strange errors sometimes:

```
NotAcceptableError: Not Acceptable
    at /Users/markus/.node_modules/lib/node_modules/jspm-server/node_modules/serve-index/index.js:169:32
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Still investigating when exactly it happens.

**Comment by dpsthree** [comment]
I'm not sure that this is related to jspm-server. I have the same problem with live-server. Still trying to track it down myself.
